version: 2
updates:
  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      # Prefix all commit messages with "MOB-0000: "
      prefix: "MOB-0000"
