disabled_rules:
  - identifier_name
  - void_function_in_ternary
  - todo
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true
included:
  - KarhooUISDK
excluded:
  - Pods
line_length: 200
# they can set both implicitly with an array
type_body_length:
  - 500 # warning
  - 501 # error
file_length:
  warning: 500
  error: 501
function_body_length:
  warning: 80
  error: 100
type_name:
  allowed_symbols: "_"
opt_in_rules:
  - closure_body_length:
      warning: 20
      error: 50
  - implicit_return: true
  - anyobject_protocol: true
  - closure_end_indentation:
      warning: 2
  - closure_spacing:
      warning: 2
  - collection_alignment: true
  - convenience_type: true
  - discouraged_optional_boolean: true
  - discouraged_optional_collection: true
  - indentation_width:
      warning: 10
  - implicitly_unwrapped_optional: true
  - multiline_function_chains: true
  - multiline_literal_brackets: true
  - operator_usage_whitespace: true
  - private_action: true
  - private_outlet: true
  - redundant_nil_coalescing: true
