blank_issues_enabled: false
contact_links:
  - name: Karhoo Developer Site
    url: developer.karhoo.com
    about: You may find answers to your questions here
  - name: Karhoo website
    url: karhoo.com
    about: The main Karhoo Website. You can contact us from here.
